import { Quote, Supplier, User, RolePerms } from './types';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 1,
    name: 'Công ty TNHH Minh Khang',
    phone: '028 3844 1234',
    email: 'info@minhkhang.com.vn',
    address: '124 Nguyễn Đình Chiểu, Q3, Tp.HCM',
    taxCode: '0304567890',
    contactPerson: 'Nguyễn Minh Khang',
    note: 'Nhà phân phối tủ Rack APC và thiết bị điện uy tín.'
  },
  {
    id: 2,
    name: 'Viễn Đông Tech',
    phone: '028 3930 5566',
    email: 'contact@viendongtech.vn',
    address: '45 Trần Hưng Đạo, Q1, Tp.HCM',
    taxCode: '0309876543',
    contactPerson: 'Trần Quốc Bảo',
    note: 'Đơn vị tích hợp linh hoạt camera và thiết bị lưu trữ.'
  },
  {
    id: 3,
    name: 'NetViet Distribution',
    phone: '024 3755 8899',
    email: 'sales@netviet.com.vn',
    address: '18 Duy Tân, Cầu Giấy, Hà Nội',
    taxCode: '0104321098',
    contactPerson: 'Lê Văn Nam',
    note: 'Phân phối chính ngạch thiết bị mạng Cisco, Palo Alto tại Việt Nam.'
  },
  {
    id: 4,
    name: 'An Ninh Việt',
    phone: '028 3899 9999',
    email: 'support@anninhviet.vn',
    address: '320 Điện Biên Phủ, Q.Bình Thạnh, Tp.HCM',
    taxCode: '0310293847',
    contactPerson: 'Phạm Thị Hoàng Hà',
    note: 'Đối tác chiến lược Hikvision khu vực phía Nam.'
  },
  {
    id: 5,
    name: 'Dell Vietnam',
    phone: '1800 54 54 55',
    email: 'dell_support_vn@dell.com',
    address: 'Tầng 15, Toà nhà Saigon Tower, 29 Lê Duẩn, Q1, Tp.HCM',
    taxCode: '0301112223',
    contactPerson: 'Steve Nguyen',
    note: 'Ủy quyền bảo hành ProSupport Next Business Day.'
  },
  {
    id: 6,
    name: 'CableVN',
    phone: '028 3512 3456',
    email: 'sales@cablevn.com',
    address: '88 Ung Văn Khiêm, Q.Bình Thạnh, Tp.HCM',
    taxCode: '0312456789',
    contactPerson: 'Michael Doan',
    note: 'Nhà cung ứng cáp CommScope và phụ kiện mạng cáp quang.'
  },
  {
    id: 7,
    name: 'Điện máy Sài Gòn',
    phone: '1900 6000',
    email: 'dienmaysaigon@sg.vn',
    address: '150 Cách Mạng Tháng Tám, Q3, Tp.HCM',
    taxCode: '0301357924',
    contactPerson: 'Vũ Minh Tuấn',
    note: 'Đại lý phân phối uỷ quyền Daikin, Panasonic.'
  },
  {
    id: 8,
    name: 'CyberSec VN',
    phone: '028 7300 1199',
    email: 'licensing@cybersec.vn',
    address: 'Hải Triều, Q1, Tp.HCM (Tòa nhà Bitexco)',
    taxCode: '0314223344',
    contactPerson: 'Trương Hoàng Quân',
    note: 'Cung cấp giải pháp an ninh mạng cao cấp Palo Alto, Fortinet.'
  }
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 1,
    device: 'UPS Online 10KVA',
    model: 'SRT10KXLI',
    brand: 'APC',
    origin: 'Mỹ',
    spec: '10KVA/10KW, 230VAC, 3 pha vào 1 pha ra, pin 12V 7AH x20, LCD display, RS232/USB',
    supplier: 'Công ty TNHH Minh Khang',
    cat: 'Điện',
    project: 'Trụ sở HCM 2026',
    price: 45000000,
    sellPrice: 54000000,
    qty: 2,
    vat: 10,
    date: '2026-05-01',
    expiry: '2026-07-01',
    status: 'Đã duyệt',
    note: 'Bảo hành 2 năm, miễn phí lắp đặt, giao trong 7 ngày'
  },
  {
    id: 2,
    device: 'UPS Online 10KVA',
    model: 'SRT10KXLI',
    brand: 'APC',
    origin: 'Mỹ',
    spec: '10KVA/10KW, 230VAC, 3 pha vào 1 pha ra, pin 12V 7AH x20',
    supplier: 'Viễn Đông Tech',
    cat: 'Điện',
    project: 'Trụ sở HCM 2026',
    price: 43500000,
    sellPrice: 52000000,
    qty: 2,
    vat: 10,
    date: '2026-05-03',
    expiry: '2026-07-03',
    status: 'Chờ duyệt',
    note: 'Hàng chính hãng, bảo hành 18 tháng'
  },
  {
    id: 3,
    device: 'Switch 48 Port PoE+',
    model: 'C9300-48P-E',
    brand: 'Cisco',
    origin: 'Mỹ',
    spec: '48x 1G PoE+ ports, 4x 10G uplink, 740W PoE budget, VLAN/QoS, Layer 3',
    supplier: 'NetViet Distribution',
    cat: 'Mạng',
    project: 'Hạ tầng mạng Q4 2026',
    price: 98700000,
    sellPrice: 118000000,
    qty: 3,
    vat: 10,
    date: '2026-04-20',
    expiry: '2026-06-20',
    status: 'Đã duyệt',
    note: ''
  },
  {
    id: 4,
    device: 'Switch 48 Port PoE+',
    model: 'C9300-48P-E',
    brand: 'Cisco',
    origin: 'Mỹ',
    spec: '48x 1G PoE+ ports, 4x 10G uplink, 740W PoE budget',
    supplier: 'Công ty TNHH Minh Khang',
    cat: 'Mạng',
    project: 'Hạ tầng mạng Q4 2026',
    price: 102000000,
    sellPrice: 122000000,
    qty: 3,
    vat: 10,
    date: '2026-04-22',
    expiry: '2026-06-22',
    status: 'Mới',
    note: 'Có phụ kiện đi kèm'
  },
  {
    id: 5,
    device: 'Camera IP Dome 4MP',
    model: 'DS-2CD2143G2-I',
    brand: 'Hikvision',
    origin: 'Trung Quốc',
    spec: '4MP, IR 40m, H.265+, IP67, IK10, Wide dynamic range, PoE 802.3af',
    supplier: 'An Ninh Việt',
    cat: 'An ninh',
    project: 'Camera giám sát 2026',
    price: 2850000,
    sellPrice: 3500000,
    qty: 20,
    vat: 10,
    date: '2026-05-10',
    expiry: '2026-08-10',
    status: 'Chờ duyệt',
    note: ''
  },
  {
    id: 6,
    device: 'Camera IP Dome 4MP',
    model: 'DS-2CD2143G2-I',
    brand: 'Hikvision',
    origin: 'Trung Quốc',
    spec: '4MP, IR 40m, H.265+, IP67, IK10, PoE',
    supplier: 'Viễn Đông Tech',
    cat: 'An ninh',
    project: 'Camera giám sát 2026',
    price: 2700000,
    sellPrice: 3300000,
    qty: 20,
    vat: 10,
    date: '2026-05-12',
    expiry: '2026-08-12',
    status: 'Mới',
    note: ''
  },
  {
    id: 7,
    device: 'Máy chủ Rack 2U',
    model: 'PowerEdge R740',
    brand: 'Dell',
    origin: 'Mỹ',
    spec: '2x Xeon Gold 6226R, 128GB RAM ECC, 4x 2.4TB SAS 10K, PERC H730P, iDRAC9',
    supplier: 'Dell Vietnam',
    cat: 'CNTT',
    project: 'Data Center HCM',
    price: 185000000,
    sellPrice: 215000000,
    qty: 1,
    vat: 10,
    date: '2026-05-05',
    expiry: '2026-06-05',
    status: 'Hết hạn',
    note: 'Hết hạn báo giá'
  },
  {
    id: 8,
    device: 'Máy chủ Rack 2U',
    model: 'PowerEdge R740',
    brand: 'Dell',
    origin: 'Mỹ',
    spec: '2x Xeon Gold 6226R, 128GB RAM ECC, 4x 2.4TB SAS 10K, PERC H730P',
    supplier: 'NetViet Distribution',
    cat: 'CNTT',
    project: 'Data Center HCM',
    price: 179000000,
    sellPrice: 215000000,
    qty: 1,
    vat: 10,
    date: '2026-05-14',
    expiry: '2026-08-14',
    status: 'Đã duyệt',
    note: 'Bảo hành 3 năm onsite next-business-day'
  },
  {
    id: 9,
    device: 'Cáp quang OM4 LC-LC',
    model: 'OM4-DUPLEX-LC-3M',
    brand: 'CommScope',
    origin: 'Mỹ',
    spec: 'OM4 50/125, LC-LC Duplex, 3 mét, LSZH jacket, màu tím',
    supplier: 'CableVN',
    cat: 'Mạng',
    project: 'Hạ tầng mạng Q4 2026',
    price: 350000,
    sellPrice: 480000,
    qty: 50,
    vat: 10,
    date: '2026-05-18',
    expiry: '2026-09-18',
    status: 'Mới',
    note: ''
  },
  {
    id: 10,
    device: 'Điều hoà Cassette 4HP',
    model: 'FCQ100KAVEA',
    brand: 'Daikin',
    origin: 'Thái Lan',
    spec: '4HP, 34.000 BTU, Inverter, 3 pha, R32, COP 3.7',
    supplier: 'Điện máy Sài Gòn',
    cat: 'Điện',
    project: 'Văn phòng tầng 5',
    price: 42500000,
    sellPrice: 51000000,
    qty: 4,
    vat: 10,
    date: '2026-05-20',
    expiry: '2026-08-20',
    status: 'Chờ duyệt',
    note: 'Lắp đặt tính phí riêng 2tr/máy'
  },
  {
    id: 11,
    device: 'Firewall NGFW',
    model: 'PA-850',
    brand: 'Palo Alto',
    origin: 'Mỹ',
    spec: 'Throughput 2.1Gbps, 64000 sessions, App-ID, URL Filtering, WildFire sandbox',
    supplier: 'CyberSec VN',
    cat: 'Mạng',
    project: 'Data Center HCM',
    price: 285000000,
    sellPrice: 342000000,
    qty: 1,
    vat: 10,
    date: '2026-05-22',
    expiry: '2026-08-22',
    status: 'Chờ duyệt',
    note: 'Gồm license 1 năm Threat Prevention'
  },
  {
    id: 12,
    device: 'Tủ mạng Rack 42U',
    model: 'NetShelter SX 42U',
    brand: 'APC',
    origin: 'Mỹ',
    spec: '42U, 600x1070mm, 1500kg load, side panels, cửa kính phía trước',
    supplier: 'Công ty TNHH Minh Khang',
    cat: 'Cơ sở hạ tầng',
    project: 'Data Center HCM',
    price: 28500000,
    sellPrice: 34200000,
    qty: 2,
    vat: 10,
    date: '2026-05-15',
    expiry: '2026-08-15',
    status: 'Đã duyệt',
    note: 'Giao hàng kèm lắp đặt'
  }
];

export const INITIAL_USERS: Record<string, User> = {
  admin: {
    username: 'admin',
    password: 'admin123',
    name: 'Admin',
    role: 'admin',
    display: 'Quản trị viên'
  },
  sales: {
    username: 'sales',
    password: 'sales123',
    name: 'Nguyễn Sales',
    role: 'sales',
    display: 'Phòng Kinh doanh'
  },
  accountant: {
    username: 'accountant',
    password: 'acc123',
    name: 'Trần Kế Toán',
    role: 'accountant',
    display: 'Phòng Kế toán'
  },
  viewer: {
    username: 'viewer',
    password: 'view123',
    name: 'Khách Xem',
    role: 'viewer',
    display: 'Khách tham khảo'
  }
};

export const INITIAL_ROLE_PERMS: Record<string, RolePerms> = {
  admin: {
    seeCost: true,
    seeSell: true,
    seeProfit: true,
    canAdd: true,
    canEdit: true,
    canDelete: true,
    canImport: true,
    canAccessSupplier: true
  },
  sales: {
    seeCost: false,
    seeSell: true,
    seeProfit: true,
    canAdd: true,
    canEdit: true,
    canDelete: false,
    canImport: false,
    canAccessSupplier: true
  },
  accountant: {
    seeCost: true,
    seeSell: false,
    seeProfit: true,
    canAdd: false,
    canEdit: false,
    canDelete: false,
    canImport: false,
    canAccessSupplier: true
  },
  viewer: {
    seeCost: false,
    seeSell: false,
    seeProfit: false,
    canAdd: false,
    canEdit: false,
    canDelete: false,
    canImport: false,
    canAccessSupplier: false
  }
};
